apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-frontend
  template:
    metadata:
      labels:
        app: chatapp-frontend
    spec:
      containers:
        - name: frontend
          image: lethanhlong/chatapp-frontend:ee0744ae1069d46e00dcee9166b1041b3d1d4071
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-frontend
spec:
  type: NodePort
  selector:
    app: chatapp-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080