apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatapp-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-db
  template:
    metadata:
      labels:
        app: chatapp-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: chatapp
            - name: POSTGRES_PASSWORD
              value: chatapp
            - name: POSTGRES_DB
              value: chatapp
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: chatapp-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-db
spec:
  selector:
    app: chatapp-db
  ports:
    - port: 5432
      targetPort: 5432